### ISSUE TITLE
Feature request: allow boards smaller than 8x8

### ISSUE THREAD

**Issue by slolo2000** [ajax333221/isepic-chess-ui#19]
Hello,

Some games (problems for young players for example) require boards which are smaller than 8x8.

Do you think you could add the ability to create smaller boards than 8x8?

For example, it could be nice to initialize the board with FEN string like: 3k2/1Qnp2/2r3/3N2/6/K5 w - - 1 1

Thanks in advance for your answer and have a nice day.

**Comment by ajax333221** [comment]
I will leave this open for a big while, no immediate plans on doing this, I will likely do Chess960 (Fischer random) first, but even that one might take me a while.

So I wouldn't expect it anytime soon but it looks like a fun nice feature to have.

**Comment by ajax333221** [comment]
actually, I need to admit the way I coded this thing is **very** hard to implement this, if I try to use anything instead 8x8 the code will explode.

sorry but this is not realisticly going to happen without some big major rewrite :/
