### ISSUE TITLE
NuxtJS compatibility?

### ISSUE THREAD

**Issue by scalemaildev** [ajax333221/isepic-chess-ui#22]
Are isepic-chess and its UI compatible as Nuxt modules? Has anyone tried this yet?

**Comment by ajax333221** [comment]
I am not familiar with Nuxt sorry.

I am planing some day to use Vue.js to solve the #8 issue of multiple boards, maybe as a separated repo and throw in some Vuetify too.

I don't know if it works on Nuxt, I will maybe give it a try some day but I'm a bit slow in these kind of things, sorry I was not of much help, I will leave this open until I do some research or somewhere else with more knowledge about it says something.
